version: "2.0"

services:
  a7:
    build:
      context: .
    environment:
      # Path to the assets root directory path (default: /assets)
      - A7_VOLUME_MOUNT_PATH=/assets
      # Allow to navigate through the indexed assets (default: true)
      # - A7_AUTOINDEX=false
      # Apply a CORS <*> rule for API catalog queries (default: true)
      # - A7_AUTOINDEX_CORS_ALL=false
      # Allow the directories and subdirectories download as a single zip file (default: true)
      # - A7_ZIP_DIRECTORIES=false
      # Allow for API meta queries (default: true)
      # - A7_META_QUERIES=false
      # Apply a CORS <*> rule for API meta queries (default: true)
      # - A7_META_QUERIES_CORS_ALL=false
      # Apply a CORS <*> rule for assets to be accessed from whatever origin (default: true)
      # - A7_CORS_ALL=false
      # Apply semantic-versioning-aware smart redirects (default: true)
      # - A7_PATH_AUTO_EXPAND=false
      # Initialize/generate the .directory.txt metadata files in every assets subfolders (default: true)
      # - A7_PATH_AUTO_EXPAND_INIT=false
      # Only run scripts; do not start the server (default: false)
      # - A7_RUN_SCRIPTS_ONLY=true
      # Only respond to HEAD and GET requests (default: true)
      # - A7_GET_REQUESTS_ONLY=false
      # Activate A7 internal API (note: writing files to disk needs write permissions) (default: true)
      # - A7_INTERNAL_API=false
      # Set the service title (displayed in the browsing UI)
      # - A7_TITLE=Clown
      # Set the service icon (displayed in the browsing UI)
      # - A7_ICON=ðŸ¤¡
    ports:
      # ASSET:ASSET â†“
      - 45537:45537
    volumes:
      - ./assets:/assets
